import 'package:flutter/material.dart';

import 'setting_item.dart';

enum AvailableCurrencies {
  USD,
  BTC,
  ARS,
  AUD,
  BDT,
  BHD,
  BMD,
  BRL,
  CAD,
  CHF,
  CLP,
  CNY,
  CZK,
  DKK,
  EUR,
  GBP,
  HKD,
  HUF,
  IDR,
  ILS,
  INR,
  JPY,
  KRW,
  KWD,
  LKR,
  MMK,
  MXN,
  MYR,
  NGN,
  NOK,
  NZD,
  PHP,
  PKR,
  PLN,
  RUB,
  SAR,
  SEK,
  SGD,
  THB,
  TRY,
  TWD,
  AED,
  UAH,
  VEF,
  VND,
  ZAR,
}

/// Represent the available currency our app supports
class AvailableCurrency extends SettingSelectionItem {
  final AvailableCurrencies currency;

  const AvailableCurrency(this.currency);

  String get name => currency.name;

  String getDisplayName(BuildContext context) {
    return symbol + ' ' + getDisplayNameNoSymbol();
  }

  String getDisplayNameNoSymbol() {
    return switch (currency) {
      AvailableCurrencies.USD => 'US Dollar',
      AvailableCurrencies.BTC => 'Bitcoin',
      AvailableCurrencies.ARS => 'Argentine Peso',
      AvailableCurrencies.AUD => 'Australian Dollar',
      AvailableCurrencies.AED => 'UAE Dirham',
      AvailableCurrencies.BDT => 'Bangladeshi Taka',
      AvailableCurrencies.BHD => 'Bahraini Dinar',
      AvailableCurrencies.BMD => 'Bermudian Dollar',
      AvailableCurrencies.BRL => 'Brazilian Real',
      AvailableCurrencies.CAD => 'Canadian Dollar',
      AvailableCurrencies.CHF => 'Swiss Franc',
      AvailableCurrencies.CLP => 'Chilean Peso',
      AvailableCurrencies.CNY => 'Chinese Yuan',
      AvailableCurrencies.CZK => 'Czech Koruna',
      AvailableCurrencies.DKK => 'Danish Krone',
      AvailableCurrencies.EUR => 'Euro',
      AvailableCurrencies.GBP => 'Great Britain Pound',
      AvailableCurrencies.HKD => 'Hong Kong Dollar',
      AvailableCurrencies.HUF => 'Hungarian Forint',
      AvailableCurrencies.IDR => 'Indonesian Rupiah',
      AvailableCurrencies.ILS => 'Israeli Shekel',
      AvailableCurrencies.INR => 'Indian Rupee',
      AvailableCurrencies.JPY => 'Japanese Yen',
      AvailableCurrencies.KRW => 'South Korean Won',
      AvailableCurrencies.KWD => 'Kuwaiti Dinar',
      AvailableCurrencies.LKR => 'Sri Lankan Rupee',
      AvailableCurrencies.MMK => 'Myanmar Kyat',
      AvailableCurrencies.MXN => 'Mexican Peso',
      AvailableCurrencies.MYR => 'Malaysian Ringgit',
      AvailableCurrencies.NGN => 'Nigerian Naira',
      AvailableCurrencies.NOK => 'Norwegian Krone',
      AvailableCurrencies.NZD => 'New Zealand Dollar',
      AvailableCurrencies.PHP => 'Philippine Peso',
      AvailableCurrencies.PKR => 'Pakistani Rupee',
      AvailableCurrencies.PLN => 'Polish Zloty',
      AvailableCurrencies.RUB => 'Russian Ruble',
      AvailableCurrencies.SAR => 'Saudi Riyal',
      AvailableCurrencies.SEK => 'Swedish Krona',
      AvailableCurrencies.SGD => 'Singapore Dollar',
      AvailableCurrencies.THB => 'Thai Baht',
      AvailableCurrencies.TRY => 'Turkish Lira',
      AvailableCurrencies.TWD => 'Taiwan Dollar',
      AvailableCurrencies.VEF => 'Venezuelan Bolivar',
      AvailableCurrencies.ZAR => 'South African Rand',
      AvailableCurrencies.UAH => 'Ukraine Hryvnia',
      AvailableCurrencies.VND => 'Vietnamese Đồng',
    };
  }

  String get symbol {
    return switch (currency) {
      AvailableCurrencies.BTC => '₿',
      AvailableCurrencies.USD => '\$',
      AvailableCurrencies.ARS => '\$',
      AvailableCurrencies.AUD => '\$',
      AvailableCurrencies.AED => 'د.إ',
      AvailableCurrencies.BDT => '৳',
      AvailableCurrencies.BHD => '.د.ب',
      AvailableCurrencies.BMD => '\$',
      AvailableCurrencies.BRL => 'R\$',
      AvailableCurrencies.CAD => '\$',
      AvailableCurrencies.CHF => 'CHF',
      AvailableCurrencies.CLP => '\$',
      AvailableCurrencies.CNY => '¥',
      AvailableCurrencies.CZK => 'Kč',
      AvailableCurrencies.DKK => 'kr.',
      AvailableCurrencies.EUR => '€',
      AvailableCurrencies.GBP => '£',
      AvailableCurrencies.HKD => 'HK\$',
      AvailableCurrencies.HUF => 'Ft',
      AvailableCurrencies.IDR => 'Rp',
      AvailableCurrencies.ILS => '₪',
      AvailableCurrencies.INR => '₹',
      AvailableCurrencies.JPY => '¥',
      AvailableCurrencies.KRW => '₩',
      AvailableCurrencies.KWD => 'KD',
      AvailableCurrencies.LKR => 'Rs',
      AvailableCurrencies.MMK => 'Ks.',
      AvailableCurrencies.MXN => '\$',
      AvailableCurrencies.MYR => 'RM',
      AvailableCurrencies.NGN => '₦',
      AvailableCurrencies.NOK => 'kr',
      AvailableCurrencies.NZD => '\$',
      AvailableCurrencies.PHP => '₱',
      AvailableCurrencies.PKR => 'Rs',
      AvailableCurrencies.PLN => 'zł',
      AvailableCurrencies.RUB => '\u20BD',
      AvailableCurrencies.SAR => 'SR',
      AvailableCurrencies.SEK => 'kr',
      AvailableCurrencies.SGD => '\$',
      AvailableCurrencies.THB => '฿',
      AvailableCurrencies.TRY => '₺',
      AvailableCurrencies.TWD => 'NT\$',
      AvailableCurrencies.VEF => 'Bs.F',
      AvailableCurrencies.ZAR => 'R\$',
      AvailableCurrencies.UAH => '₴',
      AvailableCurrencies.VND => '₫',
    };
  }

  // For saving to shared prefs
  String getId() => currency.name;
}
